package io.henrikhorbovyi.moviesapp.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF8440a4)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFf9d8ff)
val md_theme_light_onPrimaryContainer = Color(0xFF310049)
val md_theme_light_secondary = Color(0xFF69596d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf0dcf3)
val md_theme_light_onSecondaryContainer = Color(0xFF231728)
val md_theme_light_tertiary = Color(0xFF815251)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad8)
val md_theme_light_onTertiaryContainer = Color(0xFF331011)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFffffff)
val md_theme_light_onBackground = Color(0xFF1d1b1e)
val md_theme_light_surface = Color(0xFFfafafa)
val md_theme_light_onSurface = Color(0xFF1d1b1e)
val md_theme_light_surfaceVariant = Color(0xFFebdfea)
val md_theme_light_onSurfaceVariant = Color(0xFF4c444d)
val md_theme_light_outline = Color(0xFF7d747e)
val md_theme_light_inverseOnSurface = Color(0xFFf6eef3)
val md_theme_light_inverseSurface = Color(0xFF332f33)

val md_theme_dark_primary = Color(0xFFebb2ff)
val md_theme_dark_onPrimary = Color(0xFF510272)
val md_theme_dark_primaryContainer = Color(0xFF6a268a)
val md_theme_dark_onPrimaryContainer = Color(0xFFf9d8ff)
val md_theme_dark_secondary = Color(0xFFd4c0d8)
val md_theme_dark_onSecondary = Color(0xFF392c3e)
val md_theme_dark_secondaryContainer = Color(0xFF504254)
val md_theme_dark_onSecondaryContainer = Color(0xFFf0dcf3)
val md_theme_dark_tertiary = Color(0xFFf4b7b5)
val md_theme_dark_onTertiary = Color(0xFF4c2525)
val md_theme_dark_tertiaryContainer = Color(0xFF663b3a)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad8)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1b1e)
val md_theme_dark_onBackground = Color(0xFFe8e0e5)
val md_theme_dark_surface = Color(0xFF1d1b1e)
val md_theme_dark_onSurface = Color(0xFFe8e0e5)
val md_theme_dark_surfaceVariant = Color(0xFF4c444d)
val md_theme_dark_onSurfaceVariant = Color(0xFFcec3cd)
val md_theme_dark_outline = Color(0xFF978e97)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe8e0e5)

val seed = Color(0xFF732f93)
val error = Color(0xFFba1b1b)